Fix "TypeError: require(...).then is not a function" from shared bundle (#6576)
* Add test for internalized shared bundle import

* Internalize async dependencies after optimization as well

* Add side-effect noop utility